language: node_js

node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"

before_install:
  - export PATH=./node_modules/.bin/:$PATH
  - npm install -g npm
  - npm update
  
install:
  - npm install
  - npm run test
  - npm run coveralls

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - v.michael@pulse.digital
    on_success: never
    on_failure: always

env:
  - LANG="en_US.UTF-8"
os:
  - linux

dist: bionic
